# Generated by Django 3.1.1 on 2020-09-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='data', max_length=150),
            preserve_default=False,
        ),
    ]
